# Huge inspiration from:
# https://github.com/wireshark/wireshark/blob/master/.travis.yml

notifications:
  email:
    if: env(MOODLE_EMAIL) != no

language: shell

os: windows

git:
  autocrlf: input # Travis windows goes to "true" meaning all files become CRLF ended. We don't want that.

branches:
  except:
    - master
    - /MOODLE_[0-9]+_STABLE/
    - /^v[0-9]+\.[0-9]+\.[0-9]+.*/

env:
  - PHP_VERSION=7.3.25 DB=pgsql   FILTER='/::test_[a-d]/'
  - PHP_VERSION=7.3.25 DB=pgsql   FILTER='/::test_[e-l]/'
  - PHP_VERSION=7.3.25 DB=pgsql   FILTER='/::test_([m-z]|[^a-z])/'

  - PHP_VERSION=7.3.25 DB=mariadb FILTER='/::test_[a-b]/'
  - PHP_VERSION=7.3.25 DB=mariadb FILTER='/::test_c[a-o]/'
  - PHP_VERSION=7.3.25 DB=mariadb FILTER='/::test_c[^a-o]/'
  - PHP_VERSION=7.3.25 DB=mariadb FILTER='/::test_[d-e]/'
  - PHP_VERSION=7.3.25 DB=mariadb FILTER='/::test_[f]/'
  - PHP_VERSION=7.3.25 DB=mariadb FILTER='/::test_[g]/'
  - PHP_VERSION=7.3.25 DB=mariadb FILTER='/::test_[h-j]/'
  - PHP_VERSION=7.3.25 DB=mariadb FILTER='/::test_[k-m]/'
  - PHP_VERSION=7.3.25 DB=mariadb FILTER='/::test_[n-t]/'
  - PHP_VERSION=7.3.25 DB=mariadb FILTER='/::test_([u-z]|[^a-z])/'

  - PHP_VERSION=8.0.3 DB=pgsql   FILTER='/::test_[a-d]/'
  - PHP_VERSION=8.0.3 DB=pgsql   FILTER='/::test_[e-l]/'
  - PHP_VERSION=8.0.3 DB=pgsql   FILTER='/::test_([m-z]|[^a-z])/'

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/AppData/Local/Temp/chocolatey

before_install:
  # Enable long paths for windows10 and up. Some tests use looong paths (see MDL-69975, MDL-62617...)
  # Disabled because it's not wroking as expected over all PHP versions (only with super-new php73 and up)
  #- ./.travis_long_paths.bat

install:
  # just in case you want to know it :-)
  - export PPWWDD=youfoundme010
  - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
  # download and configure CA certs and configure php to use them (no check cert, coz windows misses haxx.se one)
  - wget https://curl.haxx.se/ca/cacert.pem -O /c/tools/php/cacert.pem --no-check-certificate
  - sed -i -e "s%;curl.cainfo =%curl.cainfo=\"C://tools/php/cacert.pem\"%" /c/tools/php/php.ini
    # define where the extensions dir is (not all php versions have it defined)
  - sed -i -e "s%;extension_dir = \"ext\"%extension_dir = \"ext\"%" /c/tools/php/php.ini
  # install xmlrpc-beta for php8 and up
  - if [[ ${PHP_VERSION:0:1} -gt 7 ]]; then pecl install xmlrpc-beta; fi
  # enable the extensions we need
  - sed -i -re "s%;extension=(php_)?mbstring%extension=\1mbstring%" /c/tools/php/php.ini
  - sed -i -re "s%;extension=(php_)?curl%extension=\1curl%" /c/tools/php/php.ini
  - sed -i -re "s%;extension=(php_)?fileinfo%extension=\1fileinfo%" /c/tools/php/php.ini
  - sed -i -re "s%;extension=(php_)?gd%extension=\1gd%" /c/tools/php/php.ini
  - sed -i -re "s%;extension=(php_)?intl%extension=\1intl%" /c/tools/php/php.ini
  - sed -i -re "s%;extension=(php_)?mysqli%extension=\1mysqli%" /c/tools/php/php.ini
  - sed -i -re "s%;extension=(php_)?openssl%extension=\1openssl%" /c/tools/php/php.ini
  - sed -i -re "s%;extension=(php_)?pgsql%extension=\1pgsql%" /c/tools/php/php.ini
  - sed -i -re "s%;extension=(php_)?soap%extension=\1soap%" /c/tools/php/php.ini
  - sed -i -re "s%;extension=(php_)?sodium%extension=\1sodium%" /c/tools/php/php.ini
  - sed -i -re "s%;extension=(php_)?xmlrpc%extension=\1xmlrpc%" /c/tools/php/php.ini
  # php8 requirement
  - echo 'max_input_vars=5000' >> /c/tools/php/php.ini
  # need a openssl.cnf, let's provide it
  - export OPENSSL_CONF=/c/tools/php/extras/ssl/openssl.cnf
  - export PATH=/c/tools/php:$PATH
  - >
    if [ "$DB" = 'pgsql' ]; then
      choco install postgresql10 --package-parameters="/Password:$PPWWDD" --ia "--prefix C:\tools\postgres"
      export PATH=/c/tools/postgres/bin:$PATH
    fi
  - >
    if [ "$DB" = 'mysqli' ]; then
      choco install mysql --package-parameters="/installLocation:c:\tools\mysql"
      export PATH=/c/tools/mysql/bin:$PATH
    fi
  - >
    if [ "$DB" = 'mariadb' ]; then
      choco install mariadb --ia "INSTALLDIR=C:\tools\mariadb PASSWORD=$PPWWDD"
      export PATH=/c/tools/mariadb/bin:$PATH
    fi

before_script:
  # prepare config
  - cp config-dist.php config.php

  # create dataroot dirs
  - mkdir -p "C://Users/travis/roots/data"
  - mkdir -p "C://Users/travis/roots/phpunitdata"

  # database name and password
  - sed -i -e "s%= 'moodle'%= 'travis_ci_test'%" config.php
  - sed -i -e "s%= 'password'%= '$PPWWDD'%" config.php

  # site wwwroot and dataroot
  - sed -i -e "s%http://example.com/moodle%https://localhost%" config.php
  - sed -i -e "s%/home/example/moodledata%C://Users/travis/roots/data%" config.php

  # phpunit dataroot and prefix
  - sed -i -e "/require_once/i \\\$CFG->phpunit_dataroot = 'C://Users/travis/roots/phpunitdata';" config.php
  - sed -i -e "/require_once/i \\\$CFG->phpunit_prefix = 'p_';" config.php

  # postgres setup
  - >
    if [ "$DB" = 'pgsql' ]; then
      sed -i -e "s%= 'username'%= 'postgres'%" config.php

      PGPASSWORD=$PPWWDD winpty -Xallow-non-tty -Xplain psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
    fi

  # mysql setup
  - >
    if [ "$DB" = 'mysqli' ]; then
      sed -i -e "s%= 'pgsql'%= 'mysqli'%" config.php
      sed -i -e "s%= 'username'%= 'root'%" config.php
      sed -i -e "s%=> 'utf8mb4_unicode_ci'%=> 'utf8mb4_bin'%" config.php

      MYSQL_PWD=$PPWWDD mysql -u root -e 'SET GLOBAL innodb_file_per_table=ON;'
      # Little bit of tunning (we don't care power failures, this is disposable
      MYSQL_PWD=$PPWWDD mysql -u root -e 'SET GLOBAL innodb_flush_log_at_trx_commit=0;'
      MYSQL_PWD=$PPWWDD mysql -u root -e 'CREATE DATABASE travis_ci_test DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin;'
    fi

  # mariadb setup
  - >
    if [ "$DB" = 'mariadb' ]; then
      sed -i -e "s%= 'pgsql'%= 'mariadb'%" config.php
      sed -i -e "s%= 'username'%= 'root'%" config.php
      sed -i -e "s%=> 'utf8mb4_unicode_ci'%=> 'utf8mb4_bin'%" config.php

      MYSQL_PWD=$PPWWDD mysql -u root -e 'SET GLOBAL innodb_file_per_table=ON;'
      # Little bit of tunning (we don't care power failures, this is disposable
      MYSQL_PWD=$PPWWDD mysql -u root -e 'SET GLOBAL innodb_flush_log_at_trx_commit=0;'
      MYSQL_PWD=$PPWWDD mysql -u root -e 'CREATE DATABASE travis_ci_test DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin;'
    fi

  # init phpunit
  - php admin/tool/phpunit/cli/init.php

script:
    - vendor/bin/phpunit --verbose --filter $FILTER
